### PR TITLE
Reorder files for PlatformIO to work with this lib and fix include paths

### PR DESCRIPTION
**Pull request by arduino12**

### CODE REVIEW

**Comment by Pillar1989** [comment]
@arduino12  can you talk more about your PR ?

**Comment by arduino12** [comment]
**Hi,**

**Thanks for your quick response!**
I love working with **[platformio](https://platformio.org/)**, each project have **[platformio.ini](https://docs.platformio.org/en/latest/projectconf/index.html)** configuration file,
This file can contain:
```
lib_deps =
    ${env.lib_deps_builtin}
    ${env.lib_deps_external}
    https://github.com/me-no-dev/ESPAsyncTCP.git
    knolleary/PubSubClient@^2.8
    paulstoffregen/OneWire
```
And pio takes care of cloning and including the repo into the Arduino environment!

But when using this lib or the one of elechouse, it only clones the PN532 folder - discarding the other PN532_* folders..
```
lib_deps =
    Wire
    SPI
    SoftwareSerial
    https://github.com/don/NDEF.git
    ; https://github.com/adafruit/Adafruit-PN532.git ; compiles
    ; https://github.com/Seeed-Studio/PN532.git      ; complain missing PN532_I2C.h and other headers
    ; https://github.com/elechouse/PN532.git         ; complain missing PN532_I2C.h and other headers
    https://github.com/arduino12/PN532.git           ; compiles (this is my PR)
```

I think it is related to a backward-compatibility stuff - old arduino libs structure:
```
|--PN532
  |--docs
  |--examples
  |--PN532
    |- PN532.c
    |- PN532.h
```
**But now it need to be like:**
```
|--PN532
  |--docs
  |--examples
  |--src
  |  |- PN532.c
  |  |- PN532.h
  |-- library.properties
```

Please see the files I changed and moved in my PR for full understanding-
now I can confirm my PR compiles with pio and works on my hardware :)

**Comment by hansmbakker** [comment]
@arduino12 great work, this is really helpful!

@Pillar1989 is this something you could merge?

**Comment by Cincinnatu** [comment]
Hello. I will check soon whether this is effective and reasonable.

**Pull request closed without merging**
